// Language translations
const translations = {
    en: {
        // Header
        'header.title': 'Home Health Care',
        
        // Navigation
        'nav.home': 'Home',
        'nav.about': 'About Us',
        'nav.services': 'Services',
        'nav.insurance': 'Insurance',
        'nav.contact': 'Contact',
        'nav.testimonials': 'Testimonials',
        'nav.careers': 'Careers',
        'nav.faqs': 'FAQs',
        'nav.resources': 'Resources',
        
        // Hero Section
        'hero.title': 'Welcome to <span class="priority-text">Patients Choice Home Health</span>',
        'hero.subtitle': 'Where compassionate care and clinical excellence come together in the comfort of your home. For over 20 years, we\'ve proudly served the residents of Miami-Dade and Monroe Counties, bringing skilled nursing, rehabilitation, and personal care directly to our patients\' homes.',
        'hero.philosophy': 'At Patients Choice, we believe that healing happens best at home – where patients feel secure, supported, and surrounded by family. Whether you\'re recovering from surgery, managing a chronic condition, or simply need help with daily care, we are here for you.',
        'hero.expertise': 'Our experienced, licensed clinicians and caregivers work in close coordination with your physician to deliver safe, individualized home health services that promote independence, dignity, and well-being.',
        'hero.requestCare': 'Request Care',
        'hero.ourServices': 'Our Services',

        // Services Section
        'services.title': 'Our Services',
        'services.subtitle': 'Patients Choice offers a wide range of Medicare-certified and insurance-covered home health services, plus private-pay packages for postoperative and cosmetic surgery recovery. Professional nursing care in the comfort of your home.',
        
        'services.skilledNursing': 'Skilled Nursing',
        'services.skilledNursing.bullet1': 'Diabetic Care and Teaching',
        'services.skilledNursing.bullet2': 'Respiratory Disorders (COPD)',
        'services.skilledNursing.bullet3': 'IV Therapy',
        'services.skilledNursing.bullet4': 'Rehabilitation Guidance',
        'services.skilledNursing.bullet5': 'Administering Injections',
        'services.skilledNursing.bullet6': 'Pain Relief / Pain Management',
        'services.skilledNursing.bullet7': 'Incontinence Management',
        'services.skilledNursing.bullet8': 'Vital Signs Monitoring',
        'services.skilledNursing.bullet9': 'Catheter Care and Maintenance',
        'services.skilledNursing.bullet10': 'Wound VAC Therapy',
        'services.skilledNursing.bullet11': 'Dressing Changes',

        'services.diabeticCare': 'Diabetic Care',
        'services.diabeticCare.bullet1': 'Blood sugar monitoring',
        'services.diabeticCare.bullet2': 'Medication/insulin administration',
        'services.diabeticCare.bullet3': 'Diabetic foot care',
        'services.diabeticCare.bullet4': 'Dietary and lifestyle education',
        'services.diabeticCare.bullet5': 'Prevention of complications',
        'services.diabeticCare.bullet6': 'Wound care and monitoring',
        'services.diabeticCare.bullet7': 'Nutrition counseling',
        'services.diabeticCare.bullet8': 'Blood pressure monitoring',
        'services.diabeticCare.bullet9': 'Exercise program guidance',
        'services.diabeticCare.bullet10': 'Family education and support',

        'services.postoperative': 'Postoperative Recovery',
        'services.postoperative.bullet1': 'Pain and wound management',
        'services.postoperative.bullet2': 'Mobility assistance',
        'services.postoperative.bullet3': 'Medication administration',
        'services.postoperative.bullet4': 'Communication with your surgeon',
        'services.postoperative.bullet5': 'Hospital-to-home transition planning',

        'services.cosmetic': 'Cosmetic Surgery Recovery',
        'services.cosmetic.bullet1': 'Transportation to/from surgery',
        'services.cosmetic.bullet2': '24-hour post-op care',
        'services.cosmetic.bullet3': 'Lymphatic drainage support',
        'services.cosmetic.bullet4': 'Dressing changes, drain monitoring',
        'services.cosmetic.bullet5': 'Private nursing & concierge care',

        'services.physicalTherapy': 'Physical Therapy',
        'services.physicalTherapy.bullet1': 'Expert therapy to help you regain strength and mobility',
        'services.physicalTherapy.bullet2': 'Post-Surgery Rehabilitation',
        'services.physicalTherapy.bullet3': 'Strength Training',
        'services.physicalTherapy.bullet4': 'Balance Improvement',
        'services.physicalTherapy.bullet5': 'Mobility Enhancement',
        'services.physicalTherapy.bullet6': 'Pain Management',
        'services.physicalTherapy.bullet7': 'Gait Training',

        'services.occupationalTherapy': 'Occupational Therapy',
        'services.occupationalTherapy.bullet1': 'Assistance in regaining independence in daily activities',
        'services.occupationalTherapy.bullet2': 'Daily Living Activities Training',
        'services.occupationalTherapy.bullet3': 'Home Safety Assessment',
        'services.occupationalTherapy.bullet4': 'Adaptive Equipment Training',
        'services.occupationalTherapy.bullet5': 'Fine Motor Skills Development',
        'services.occupationalTherapy.bullet6': 'Energy Conservation Techniques',

        'services.homeHealthAide': 'Home Health Aide',
        'services.homeHealthAide.bullet1': 'Compassionate personal care and assistance with daily activities',
        'services.homeHealthAide.bullet2': 'Personal Hygiene Assistance',
        'services.homeHealthAide.bullet3': 'Medication Reminders',
        'services.homeHealthAide.bullet4': 'Light Housekeeping',
        'services.homeHealthAide.bullet5': 'Meal Preparation',
        'services.homeHealthAide.bullet6': 'Companionship',

        'services.medicalSocialWorker': 'Medical Social Worker',
        'services.medicalSocialWorker.bullet1': 'Support in navigating healthcare and community resources',
        'services.medicalSocialWorker.bullet2': 'Resource Coordination',
        'services.medicalSocialWorker.bullet3': 'Care Planning',
        'services.medicalSocialWorker.bullet4': 'Family Support',
        'services.medicalSocialWorker.bullet5': 'Community Service Connection',
        'services.medicalSocialWorker.bullet6': 'Healthcare Navigation',

        'services.note': 'All services are delivered under the supervision of your physician and based on your personalized care plan.',
        
        // Insurance Section
        'insurance.title': 'Insurance',
        'insurance.subtitle': 'Patients Choice accepts the following plans:',
        'insurance.medicare': 'Medicare & Medicare Advantage',
        'insurance.medicareDesc': 'We accept Original Medicare and Medicare Advantage plans',
        'insurance.private': 'Private Insurance',
        'insurance.privateDesc': 'We work with most major insurance providers',
        'insurance.military': 'Military & Government',
        'insurance.militaryDesc': 'Serving our military and government personnel',
        'insurance.managed': 'Managed Care',
        'insurance.managedDesc': 'Comprehensive managed care plans',
        'insurance.longTerm': 'Long Term Care Plans',
        'insurance.longTermDesc': 'Supporting your long-term care needs',

        'insurance.longTermPlans': [
            'American Elder Care',
            'Amerigroup Florida',
            'Coventry Health Care of Florida',
            'Humana Medical Plan (Florida Comfort Choice)',
            'Independent Living',
            'Little Havana Nutrition and Activities Center',
            'Molina Complete Care',
            'Sunshine Health Plan'
        ],

        'insurance.acceptedPlans': [
            'Advantage Health Plan',
            'Aetna Health Plans',
            'Aetna Medicare Advantage',
            'Amerigroup',
            'Amerivantage',
            'Argus Home Infusion (PDP)',
            'Assurant',
            'AvMed Health Plans',
            'Beech Street',
            'Best Choice',
            'Better Health',
            'Blue Cross Blue Shield (BCBS)',
            'Blue Cross, Blue Shield',
            'CarePlus',
            'Centene',
            'CIGNA',
            'Cofinity',
            'Corvel Corporation',
            'Coventry',
            'Coventry Health Care',
            'Dimension Health / Evolutions',
            'Florida Community Care',
            'Florida Health Care Plus',
            'Focus Healthcare Management',
            'Freedom Health',
            'Great West',
            'Health Net',
            'Healthease',
            'HealthSun',
            'Healthy Kids',
            'Humana',
            'Little Havana Activities and Nutrition Centers',
            'LoveLace',
            'Magellan',
            'Medica Healthcare Plans',
            'Medicare (Original)',
            'Molina Healthcare',
            'MSC Care Management',
            'Neighborhood Health Plan',
            'Nursing Home Diversion Waiver Programs',
            'Optum Health',
            'Optum VA',
            'Physicians United Plan',
            'Preferred Medical Plan',
            'Prestige Health Plan',
            'Quality Health Plan',
            'South Florida',
            'Staywell',
            'TRICARE South Region',
            'United Behavioral Health / Optum Health',
            'United Healthcare',
            'VSHP',
            'WellCare Health Plans'
        ],

        'insurance.managedCarePlans': [
            'Florida Community Health',
            'Simply Healthcare',
            'Sunshine Health',
            'Sunshine State Health Plan (Centene)'
        ],

        'insurance.militaryPlans': [
            'Optum VA',
            'Tricare (Military Health)',
            'Humana Military'
        ],

        'insurance.privatePay': 'Private Pay Options',
        'insurance.privatePayDesc': 'We offer flexible plans for those not covered by insurance, including postoperative and cosmetic surgery packages.',
        'insurance.support': 'Insurance Support',
        'insurance.supportDesc': 'Our staff will verify your benefits, explain any costs upfront, and guide you every step of the way.',
        
        // About Section
        'about.title': 'About Us',
        'about.mission': 'Locally Trusted. Family-Focused. Clinically Strong.',
        'about.missionDesc': 'Patients Choice Home Health Agency was founded with a simple mission to provide high-quality, compassionate health care to individuals in the comfort of their homes.',
        'about.community': 'Our Community',
        'about.communityDesc': 'As a locally owned and operated agency, we understand the unique needs of our community. We serve patients across Miami-Dade and Monroe Counties, from urban centers to coastal communities.',
        'about.team': 'Our Team',
        'about.teamDesc': 'We are proud to be a Medicare-certified and AHCA-licensed home health agency. Our team includes:',
        'about.teamList': 'Each member of our staff is carefully screened, trained, and supervised to ensure our patients receive only the most reliable and compassionate care.',
        'about.philosophy': 'Our Philosophy',
        'about.philosophyDesc': 'We treat every patient as family. We listen carefully, communicate clearly, and personalize every service around the goals of the patient and their family.',
        'about.team.bullet1': 'Registered Nurses (RNs)',
        'about.team.bullet2': 'Licensed Practical Nurses (LPNs)',
        'about.team.bullet3': 'Physical & Occupational Therapists',
        'about.team.bullet4': 'Home Health Aides (HHAs & CNAs)',
        'about.team.bullet5': 'Medical Social Workers',
        'about.whyChoose.title': 'Why Choose Patients Choice?',
        'about.whyChoose.subtitle': 'Your trusted partner in home healthcare for over two decades',
        'about.whyChoose.bullet1': 'Over 20 years serving the South Florida area',
        'about.whyChoose.bullet2': 'Bilingual and culturally competent staff',
        'about.whyChoose.bullet3': 'Accepts Medicare, Medicaid, and most private insurances',
        'about.whyChoose.bullet4': '24/7 nursing support available',
        'about.whyChoose.bullet5': 'Licensed and accredited',
        'about.whyChoose.bullet6': 'Customized care plans',
        'about.whyChoose.cta': 'Contact us today for a FREE consultation.',
        'about.nonDiscrimination.title': 'Non-Discrimination Policy',
        'about.nonDiscrimination.desc': 'Patient\'s Choice Home Health Care promotes equality in providing services and employment. In observation of Title VI of the Civil Rights Act of 1964, the Age Discrimination Act of 1975 and Section 504 of the Rehabilitation Act of 1973, the company ensures that all eligible clients shall receive services due without unlawful discrimination against age, gender, color, religion, national origin, disability, race, sexual orientation or ancestry.',
        'about.professionalStandards.title': 'Professional Standards',
        'about.professionalStandards.desc': 'Our professionals at Patient\'s Choice Home Health Care are governed under the State and Federal Licenses to provide the highest quality of services to our patients and their families based on company policies and procedures.',
        'about.teamDesc2': 'To preserve the quality of our home health care programs, we employ the most qualified and compassionate professionals. We comply with all State and Federal Licensing Requirements. We make certain, that prior to initial patient care, our staff is cleared by background and license screenings. Patient safety and confidentiality is of utmost importance at Patient\'s Choice Home Health Care.',
        
        // Resources Section
        'resources.title': 'Resources',
        'resources.subtitle': 'Access these valuable healthcare resources and information to help you make informed decisions about your health.',
        'resources.welcome.title': 'Welcome to Our Resources Center',
        'resources.welcome.desc': 'Welcome to our Resources page. Here you\'ll find helpful information about insurance coverage, downloadable forms, and external links to reputable organizations. We\'ve compiled everything in one place for your convenience.',
        'resources.insurance.title': 'Insurance Information',
        'resources.insurance.desc': 'Learn about Medicare, Medicaid, and private insurance coverage options.',
        'resources.forms.title': 'Downloadable Forms',
        'resources.forms.desc': 'Access important forms for referrals, intake, and care management.',
        'resources.external.title': 'External Resources',
        'resources.external.desc': 'Find trusted organizations and agencies for additional support.',
        'resources.insurance.section.title': 'Insurance and Medicare/Medicaid Information',
        'resources.insurance.section.desc': 'We accept multiple insurance plans to make our home health services accessible. Below is a summary of coverage options and how home health care is covered:',
        'resources.medicare.title': 'Medicare Coverage',
        'resources.medicare.bullet1': '100% coverage for approved home health services',
        'resources.medicare.bullet2': 'Doctor must certify intermittent skilled care need',
        'resources.medicare.bullet3': 'Must be homebound (difficult to leave without assistance)',
        'resources.medicare.bullet4': 'Face-to-face evaluation required',
        'resources.medicare.bullet5': 'Services by Medicare-certified agency only',
        'resources.medicare.link': 'For more details on Medicare eligibility and benefits, visit the official Medicare website.',
        'resources.medicaid.title': 'Florida Medicaid',
        'resources.medicaid.bullet1': 'Covers home health services for eligible individuals',
        'resources.medicaid.bullet2': 'Includes skilled nursing visits and therapy',
        'resources.medicaid.bullet3': 'Based on medical necessity',
        'resources.medicaid.bullet4': 'Income/assets criteria apply',
        'resources.medicaid.link': 'To learn more or apply for Florida Medicaid, visit the Florida Department of Children and Families\' ACCESS Florida portal.',
        'resources.private.title': 'Private Insurance',
        'resources.private.bullet1': 'Most major insurance plans accepted',
        'resources.private.bullet2': 'HMOs, PPOs, and managed care plans',
        'resources.private.bullet3': 'Coverage verification service available',
        'resources.private.bullet4': 'Staff assistance with benefits and authorizations',
        'resources.insurance.note': 'If you have questions about your coverage or eligibility, feel free to call us. We can help you understand your plan\'s home health benefits and even direct you to the right resources (such as Medicare or Medicaid information tools) for further information.',
        'resources.forms.section.title': 'Downloadable Forms',
        'resources.forms.section.desc': 'For your convenience, we provide important forms that you can download, print, or fill out to expedite your care process. Below are the forms available (in PDF format and, where noted, as fillable electronic forms):',
        'resources.forms.referral.title': 'Referral Form',
        'resources.forms.referral.desc': 'For physicians, hospitals, or clinics to refer a patient. Includes sections for patient information, diagnosis, requested services, and physician signature. Available as printable PDF and electronic form.',
        'resources.forms.intake.title': 'New Patient Intake Packet',
        'resources.forms.intake.desc': 'Comprehensive admission packet containing patient information forms, consent for treatment, medical history questionnaire, and patient rights & responsibilities.',
        'resources.forms.hipaa.title': 'HIPAA Consent/Release Form',
        'resources.forms.hipaa.desc': 'Authorize our agency to share your protected health information with designated family members or caregivers in compliance with HIPAA regulations.',
        'resources.forms.medication.title': 'Medication List Template',
        'resources.forms.medication.desc': 'Simple worksheet to record current medications, dosages, times of day, and prescribing doctor. Useful for doctor visits and emergencies.',
        'resources.forms.caregiver.title': 'Caregiver Daily Checklist',
        'resources.forms.caregiver.desc': 'Track daily care tasks like meals, medications, exercises, vital signs, and includes a notes section for improved communication among family members and care team.',
        'resources.forms.download.note': 'Download Instructions: Click on the name of any form to download it. You may fill it out and email/fax it to us, or have it ready for the staff during the initial assessment. If you need a form in a different format or have trouble downloading, please contact our office and we can send it to you directly.',
        'resources.external.section.title': 'External Resources',
        'resources.external.section.desc': 'We have gathered a list of trusted external resources, including official health agencies and organizations, to provide you with additional information and support.',
        'resources.external.alliance.title': 'Alliance for Aging',
        'resources.external.alliance.desc': 'Miami-Dade based private, not-for-profit agency connecting seniors to services for meals, recreation, adult day care, personal care, legal help, and transportation.',
        'resources.external.elderaffairs.title': 'Florida Department of Elder Affairs',
        'resources.external.elderaffairs.desc': 'State agency dedicated to services for Florida\'s seniors, offering programs like National Family Caregiver Support, aging in place resources, and Elder Helpline.',
        'resources.external.hhs.title': 'U.S. Department of Health & Human Services',
        'resources.external.hhs.desc': 'Federal department overseeing public health, healthcare services, and programs like Medicare/Medicaid with information on national health policies.',
        'resources.external.cms.title': 'Centers for Medicare & Medicaid Services',
        'resources.external.cms.desc': 'Federal agency administering Medicare, Medicaid and CHIP, providing detailed coverage guidelines and Medicare Care Compare tools.',
        'resources.external.floridahealth.title': 'Florida Department of Health',
        'resources.external.floridahealth.desc': 'State health department with resources on public health programs, statewide health advisories, and services specific to Florida residents.',
        'resources.external.heart.title': 'American Heart Association',
        'resources.external.heart.desc': 'Leading nonprofit organization providing educational articles, healthy living tips, and support resources for heart disease and stroke recovery.',
        'resources.external.alz.title': 'Alzheimer\'s Association',
        'resources.external.alz.desc': 'National organization offering 24/7 helpline, caregiver tips, local support group finder, and latest information on Alzheimer\'s care strategies.',
        'resources.external.ama.title': 'American Medical Association',
        'resources.external.ama.desc': 'Professional association offering public health education, articles on health conditions, and tools like doctor finders and health glossaries.',
        'resources.external.caregiver.title': 'Family Caregiver Alliance',
        'resources.external.caregiver.desc': 'Nonprofit organization providing education, caregiving tips, webinars, support group information, and fact sheets for family caregivers.',
        'resources.external.nia.title': 'National Institute on Aging',
        'resources.external.nia.desc': 'Government research-based advice on home modifications, fall prevention, and independent living for seniors aging in place.',
        'resources.cta.title': 'Need More Help?',
        'resources.cta.desc': 'If you\'re looking for something not listed here – whether it\'s a specific form, information about a particular condition, or guidance on getting care – please contact us. Our team at Patient\'s Choice Home Health Care is always ready to assist you in finding the information or support you need. Remember, you are not alone – we are here to help you navigate your home health care journey every step of the way.',
        'resources.cta.button': 'Contact Us Now',
        
        // Footer
        'footer.brand': 'Patient\'s Choice',
        'footer.desc': 'Providing exceptional home health care services with compassion and professionalism. Your health and well-being are our top priorities.',
        'footer.quickLinks': 'Quick Links',
        'footer.connect': 'Connect With Us',
        'footer.copyright': '© 2025 Patient\'s Choice Home Health Care. All rights reserved.',
        'footer.address': 'Address',
        'footer.hours': 'Office Hours',
        'footer.onCall': 'On-Call Nurses Available 24/7',
        
        // Testimonials Section
        'testimonials.title': 'What Our Patients Say',
        'testimonials.subtitle': 'Hear from our patients about their experiences with Patient\'s Choice Home Health Care.',
        'testimonials.quote1': '"After my mom\'s surgery, Patients Choice came to our home. Their nurse was incredible – compassionate, gentle, and professional. I highly recommend them!"',
        'testimonials.author1': 'Maria G.',
        'testimonials.quote2': '"Thanks to their diabetic care program, my sugar levels are under control. I\'ve learned so much!"',
        'testimonials.author2': 'Carlos M.',
        'testimonials.quote3': '"They helped me recover comfortably after my cosmetic procedure. So professional and discreet!"',
        'testimonials.author3': 'Emily S.',
        
        // Careers Section
        'careers.title': 'Careers at Patient\'s Choice',
        'careers.subtitle': 'We\'re hiring compassionate professionals who want to make a difference!',
        'careers.positions': 'Now Hiring',
        'careers.position1': 'RNs / LPNs',
        'careers.position2': 'Physical & Occupational Therapists',
        'careers.position3': 'CNAs / HHAs',
        'careers.position4': 'Medical Social Workers',
        'careers.position5': 'Intake Coordinators',
        'careers.benefits': 'Benefits',
        'careers.benefit1': 'Competitive Pay',
        'careers.benefit2': 'Flexible Scheduling',
        'careers.benefit3': 'Supportive Work Environment',
        'careers.benefit4': 'Ongoing Training',
        'careers.apply': 'Apply Today',
        'careers.applyDesc': 'Send your resume to <a href="mailto:careers@patientschoice.com" class="contact-link">careers@patientschoice.com</a>',
        'careers.contact': 'Interested in being a part of our team?',
        'careers.contactDesc': 'Contact us now for more information!',
        
        // FAQs Section
        'faqs.title': 'Frequently Asked Questions',
        'faqs.subtitle': 'Find answers to common questions about our services and care.',
        'faqs.question1': 'What is home health care?',
        'faqs.answer1': 'Medical care provided in your home by nurses, therapists, and aides under a physician\'s direction.',
        'faqs.question2': 'Who qualifies?',
        'faqs.answer2': 'Patients who are homebound and require intermittent skilled care.',
        'faqs.question3': 'Is it covered by insurance?',
        'faqs.answer3': 'Yes! Medicare, Medicaid, and most private insurances cover qualified services.',
        'faqs.question4': 'Do you offer private-pay services?',
        'faqs.answer4': 'Yes – especially for cosmetic recovery and concierge care.',
        'faqs.question5': 'How do I start?',
        'faqs.answer5': 'Call us or have your doctor send a referral. We\'ll handle the rest!',

        // Contact Form Placeholders and Labels
        'contact.name.placeholder': 'Enter your full name',
        'contact.email.placeholder': 'Enter your email address',
        'contact.phone.placeholder': 'Enter your phone number',
        'contact.message.placeholder': 'Tell us about your needs',
        
        // Contact Form Service Options
        'contact.service.optgroup.nursing': 'Skilled Nursing Services',
        'contact.service.option.nursing': 'Skilled Nursing Care',
        'contact.service.option.medication': 'Medication Management',
        'contact.service.option.wound': 'Wound Care',
        'contact.service.option.monitoring': 'Health Monitoring',
        
        'contact.service.optgroup.therapy': 'Therapy Services',
        'contact.service.option.physical': 'Physical Therapy',
        'contact.service.option.occupational': 'Occupational Therapy',
        
        'contact.service.optgroup.personal': 'Personal Care Services',
        'contact.service.option.daily': 'Daily Activities Assistance',
        'contact.service.option.hygiene': 'Personal Hygiene Care',
        'contact.service.option.mobility': 'Mobility Assistance',
        
        'contact.service.optgroup.other': 'Other Services',
        'contact.service.option.caregiver': 'Caregiver Relief',
        'contact.service.option.coordination': 'Care Coordination',
        'contact.service.option.other': 'Other Services',

        'contact.address': 'Address',
        'contact.license': 'License #299992327',

        // Contact Information
        'contact.info.phone': '(305) 225-5353',
        'contact.info.fax': '(305) 225-5306',
        'contact.info.email': 'info@patients-choice.com',
        'contact.info.careers_email': 'careers@patientschoice.com',
        'contact.info.license': 'License #299992327',
        'contact.info.address.line1': '7205 NW 19th Street, Suite 201',
        'contact.info.address.line2': 'Miami, Florida 33126',
        'contact.info.hours': 'Monday–Friday, 9 AM – 5 PM',
        'contact.info.callToday': 'Call Today:',
        'contact.info.faxLabel': 'Fax:',
        'contact.info.emailLabel': 'Email:',
        'contact.info.companyName': 'Patients Choice Home Health Agency',
    },
    es: {
        // Header
        'header.title': 'Cuidado de Salud en el Hogar',
        
        // Navigation
        'nav.home': 'Inicio',
        'nav.about': 'Sobre Nosotros',
        'nav.services': 'Servicios',
        'nav.insurance': 'Seguros',
        'nav.contact': 'Contacto',
        'nav.testimonials': 'Testimonios',
        'nav.careers': 'Carreras',
        'nav.faqs': 'Preguntas Frecuentes',
        'nav.resources': 'Recursos',
        
        // Hero Section
        'hero.title': 'Bienvenido a <span class="priority-text">Patients Choice Home Health</span>',
        'hero.subtitle': 'Donde el cuidado compasivo y la excelencia clínica se unen en la comodidad de su hogar. Por más de 20 años, hemos servido con orgullo a los residentes de los condados de Miami-Dade y Monroe, brindando servicios de enfermería especializada, rehabilitación y cuidado personal directamente en los hogares de nuestros pacientes.',
        'hero.philosophy': 'En Patients Choice, creemos que la recuperación ocurre mejor en casa – donde los pacientes se sienten seguros, apoyados y rodeados de familia. Ya sea que esté recuperándose de una cirugía, manejando una condición crónica o simplemente necesite ayuda con el cuidado diario, estamos aquí para usted.',
        'hero.expertise': 'Nuestros clínicos y cuidadores experimentados y licenciados trabajan en estrecha coordinación con su médico para brindar servicios de salud en el hogar seguros e individualizados que promueven la independencia, la dignidad y el bienestar.',
        'hero.requestCare': 'Solicitar Atención',
        'hero.ourServices': 'Nuestros Servicios',

        // Services Section
        'services.title': 'Nuestros Servicios',
        'services.subtitle': 'Patients Choice ofrece una amplia gama de servicios de salud en el hogar certificados por Medicare y cubiertos por seguros, además de paquetes de pago privado para la recuperación postoperatoria y de cirugía estética. Atención de enfermería profesional en la comodidad de su hogar.',
        
        'services.skilledNursing': 'Enfermería Especializada',
        'services.skilledNursing.bullet1': 'Cuidado y Educación Diabética',
        'services.skilledNursing.bullet2': 'Trastornos Respiratorios (EPOC)',
        'services.skilledNursing.bullet3': 'Terapia IV',
        'services.skilledNursing.bullet4': 'Guía de Rehabilitación',
        'services.skilledNursing.bullet5': 'Administración de Inyecciones',
        'services.skilledNursing.bullet6': 'Alivio del Dolor / Manejo del Dolor',
        'services.skilledNursing.bullet7': 'Manejo de la Incontinencia',
        'services.skilledNursing.bullet8': 'Monitoreo de Signos Vitales',
        'services.skilledNursing.bullet9': 'Cuidado y Mantenimiento de Catéteres',
        'services.skilledNursing.bullet10': 'Terapia VAC para Heridas',
        'services.skilledNursing.bullet11': 'Cambios de Vendajes',

        'services.diabeticCare': 'Cuidado Diabético',
        'services.diabeticCare.bullet1': 'Control de azúcar en sangre',
        'services.diabeticCare.bullet2': 'Administración de medicamentos/insulina',
        'services.diabeticCare.bullet3': 'Cuidado de pies diabéticos',
        'services.diabeticCare.bullet4': 'Educación dietética y de estilo de vida',
        'services.diabeticCare.bullet5': 'Prevención de complicaciones',
        'services.diabeticCare.bullet6': 'Cuidado y monitoreo de heridas',
        'services.diabeticCare.bullet7': 'Asesoramiento nutricional',
        'services.diabeticCare.bullet8': 'Control de la presión arterial',
        'services.diabeticCare.bullet9': 'Guía de programa de ejercicios',
        'services.diabeticCare.bullet10': 'Educación y apoyo familiar',

        'services.postoperative': 'Recuperación Postoperatoria',
        'services.postoperative.bullet1': 'Manejo del dolor y heridas',
        'services.postoperative.bullet2': 'Asistencia para la movilidad',
        'services.postoperative.bullet3': 'Administración de medicamentos',
        'services.postoperative.bullet4': 'Comunicación con su cirujano',
        'services.postoperative.bullet5': 'Planificación de transición del hospital al hogar',

        'services.cosmetic': 'Recuperación de Cirugía Estética',
        'services.cosmetic.bullet1': 'Transporte hacia/desde la cirugía',
        'services.cosmetic.bullet2': 'Cuidado postoperatorio las 24 horas',
        'services.cosmetic.bullet3': 'Soporte de drenaje linfático',
        'services.cosmetic.bullet4': 'Cambios de vendajes, monitoreo de drenajes',
        'services.cosmetic.bullet5': 'Enfermería privada y atención de conserjería',

        'services.physicalTherapy': 'Terapia Física',
        'services.physicalTherapy.bullet1': 'Terapia experta para ayudarte a recuperar fuerza y movilidad',
        'services.physicalTherapy.bullet2': 'Rehabilitación Post-Quirúrgica',
        'services.physicalTherapy.bullet3': 'Entrenamiento de Fuerza',
        'services.physicalTherapy.bullet4': 'Mejora del Equilibrio',
        'services.physicalTherapy.bullet5': 'Mejora de la Movilidad',
        'services.physicalTherapy.bullet6': 'Manejo del Dolor',
        'services.physicalTherapy.bullet7': 'Entrenamiento de la Marcha',

        'services.occupationalTherapy': 'Terapia Ocupacional',
        'services.occupationalTherapy.bullet1': 'Asistencia para recuperar la independencia en actividades diarias',
        'services.occupationalTherapy.bullet2': 'Entrenamiento en Actividades de la Vida Diaria',
        'services.occupationalTherapy.bullet3': 'Evaluación de Seguridad en el Hogar',
        'services.occupationalTherapy.bullet4': 'Entrenamiento en Equipos Adaptativos',
        'services.occupationalTherapy.bullet5': 'Desarrollo de Habilidades Motoras Finas',
        'services.occupationalTherapy.bullet6': 'Técnicas de Conservación de Energía',

        'services.homeHealthAide': 'Asistente de Salud en el Hogar',
        'services.homeHealthAide.bullet1': 'Cuidado personal compasivo y asistencia con actividades diarias',
        'services.homeHealthAide.bullet2': 'Asistencia con la Higiene Personal',
        'services.homeHealthAide.bullet3': 'Recordatorios de Medicamentos',
        'services.homeHealthAide.bullet4': 'Limpieza Ligera',
        'services.homeHealthAide.bullet5': 'Preparación de Comidas',
        'services.homeHealthAide.bullet6': 'Compañía',

        'services.medicalSocialWorker': 'Trabajador Social Médico',
        'services.medicalSocialWorker.bullet1': 'Apoyo en la navegación de recursos sanitarios y comunitarios',
        'services.medicalSocialWorker.bullet2': 'Coordinación de Recursos',
        'services.medicalSocialWorker.bullet3': 'Planificación de Cuidados',
        'services.medicalSocialWorker.bullet4': 'Apoyo Familiar',
        'services.medicalSocialWorker.bullet5': 'Conexión con Servicios Comunitarios',
        'services.medicalSocialWorker.bullet6': 'Navegación del Sistema de Salud',

        'services.note': 'Todos los servicios se brindan bajo la supervisión de su médico y según su plan de atención personalizado.',
        
        // Insurance Section
        'insurance.title': 'Seguros',
        'insurance.subtitle': 'Patients Choice acepta los siguientes planes:',
        'insurance.medicare': 'Medicare y Medicare Advantage',
        'insurance.medicareDesc': 'Aceptamos Medicare Original y planes Medicare Advantage',
        'insurance.private': 'Seguros Privados',
        'insurance.privateDesc': 'Trabajamos con la mayoría de los proveedores de seguros principales',
        'insurance.military': 'Militar y Gubernamental',
        'insurance.militaryDesc': 'Sirviendo a nuestro personal militar y gubernamental',
        'insurance.managed': 'Atención Administrada',
        'insurance.managedDesc': 'Planes integrales de atención administrada',
        'insurance.longTerm': 'Planes de Cuidado a Largo Plazo',
        'insurance.longTermDesc': 'Apoyando sus necesidades de cuidado a largo plazo',
        'insurance.privatePay': 'Opciones de Pago Privado',
        'insurance.privatePayDesc': 'Ofrecemos planes flexibles para aquellos no cubiertos por seguros, incluyendo paquetes postoperatorios y de cirugía estética.',
        'insurance.support': 'Soporte de Seguros',
        'insurance.supportDesc': 'Nuestro personal verificará sus beneficios, explicará cualquier costo por adelantado y lo guiará en cada paso del proceso.',
        
        // About Section
        'about.title': 'Sobre Nosotros',
        'about.mission': 'Confiado Localmente. Enfocado en la Familia. Clínicamente Fuerte.',
        'about.missionDesc': 'Patients Choice Home Health Agency fue fundada con una misión simple: proporcionar atención médica de alta calidad y compasiva a las personas en la comodidad de sus hogares.',
        'about.community': 'Nuestra Comunidad',
        'about.communityDesc': 'Como una agencia local y operada localmente, entendemos las necesidades únicas de nuestra comunidad. Atendemos a pacientes en los condados de Miami-Dade y Monroe, desde centros urbanos hasta comunidades costeras.',
        'about.team': 'Nuestro Equipo',
        'about.teamDesc': 'Estamos orgullosos de ser una agencia de salud en el hogar certificada por Medicare y con licencia AHCA. Nuestro equipo incluye:',
        'about.teamList': 'Cada miembro de nuestro personal es cuidadosamente seleccionado, capacitado y supervisado para garantizar que nuestros pacientes reciban solo la atención más confiable y compasiva.',
        'about.philosophy': 'Nuestra Filosofía',
        'about.philosophyDesc': 'Tratamos a cada paciente como familia. Escuchamos con atención, nos comunicamos claramente y personalizamos cada servicio en torno a los objetivos del paciente y su familia.',
        'about.team.bullet1': 'Enfermeras Registradas (RN)',
        'about.team.bullet2': 'Enfermeras Prácticas Licenciadas (LPN)',
        'about.team.bullet3': 'Terapeutas Físicos y Ocupacionales',
        'about.team.bullet4': 'Asistentes de Salud en el Hogar (HHA y CNA)',
        'about.team.bullet5': 'Trabajadores Sociales Médicos',
        'about.whyChoose.title': '¿Por qué elegir Patients Choice?',
        'about.whyChoose.subtitle': 'Su socio de confianza en atención médica domiciliaria por más de dos décadas',
        'about.whyChoose.bullet1': 'Más de 20 años sirviendo al Sur de la Florida',
        'about.whyChoose.bullet2': 'Personal bilingüe y culturalmente competente',
        'about.whyChoose.bullet3': 'Se acepta Medicare, Medicaid y la mayoría de los seguros',
        'about.whyChoose.bullet4': 'Soporte de enfermería disponible 24/7',
        'about.whyChoose.bullet5': 'Licenciado y acreditado',
        'about.whyChoose.bullet6': 'Planes de atención personalizados',
        'about.whyChoose.cta': 'Contáctenos hoy para programar una consulta GRATUITA.',
        'about.nonDiscrimination.title': 'Política de No Discriminación',
        'about.nonDiscrimination.desc': 'Patient\'s Choice Home Health Care promueve la igualdad en la prestación de servicios y empleo. En observancia del Título VI de la Ley de Derechos Civiles de 1964, la Ley de Discriminación por Edad de 1975 y la Sección 504 de la Ley de Rehabilitación de 1973, la compañía asegura que todos los clientes elegibles recibirán los servicios correspondientes sin discriminación ilegal por edad, género, color, religión, origen nacional, discapacidad, raza, orientación sexual o ascendencia.',
        'about.professionalStandards.title': 'Estándares Profesionales',
        'about.professionalStandards.desc': 'Nuestros profesionales en Patient\'s Choice Home Health Care se rigen bajo las Licencias Estatales y Federales para proporcionar servicios de la más alta calidad a nuestros pacientes y sus familias según las políticas y procedimientos de la compañía.',
        'about.teamDesc2': 'Para preservar la calidad de nuestros programas de atención médica domiciliaria, empleamos a los profesionales más calificados y compasivos. Cumplimos con todos los Requisitos de Licencia Estatales y Federales. Nos aseguramos de que, antes de la atención inicial del paciente, nuestro personal sea autorizado mediante verificaciones de antecedentes y licencias. La seguridad y confidencialidad del paciente es de suma importancia en Patient\'s Choice Home Health Care.',
        
        // Resources Section
        'resources.title': 'Recursos',
        'resources.subtitle': 'Acceda a estos valiosos recursos e información de atención médica para ayudarlo a tomar decisiones informadas sobre su salud.',
        'resources.welcome.title': 'Bienvenido a Nuestro Centro de Recursos',
        'resources.welcome.desc': 'Bienvenido a nuestra página de Recursos. Aquí encontrará información útil sobre cobertura de seguros, formularios descargables y enlaces externos a organizaciones confiables. Hemos compilado todo en un solo lugar para su conveniencia.',
        'resources.insurance.title': 'Información de Seguros',
        'resources.insurance.desc': 'Conozca las opciones de cobertura de Medicare, Medicaid y seguros privados.',
        'resources.forms.title': 'Formularios Descargables',
        'resources.forms.desc': 'Acceda a formularios importantes para referencias, admisión y gestión de cuidados.',
        'resources.external.title': 'Recursos Externos',
        'resources.external.desc': 'Encuentre organizaciones y agencias confiables para apoyo adicional.',
        'resources.insurance.section.title': 'Información sobre Seguros y Medicare/Medicaid',
        'resources.insurance.section.desc': 'Aceptamos múltiples planes de seguros para hacer accesibles nuestros servicios de salud en el hogar. A continuación se muestra un resumen de las opciones de cobertura y cómo se cubre la atención médica en el hogar:',
        'resources.medicare.title': 'Cobertura de Medicare',
        'resources.medicare.bullet1': '100% de cobertura para servicios de salud en el hogar aprobados',
        'resources.medicare.bullet2': 'El médico debe certificar la necesidad de atención especializada intermitente',
        'resources.medicare.bullet3': 'Debe estar confinado en casa (dificultad para salir sin asistencia)',
        'resources.medicare.bullet4': 'Se requiere evaluación cara a cara',
        'resources.medicare.bullet5': 'Servicios solo por agencia certificada por Medicare',
        'resources.medicare.link': 'Para más detalles sobre elegibilidad y beneficios de Medicare, visite el sitio web oficial de Medicare.',
        'resources.medicaid.title': 'Medicaid de Florida',
        'resources.medicaid.bullet1': 'Cubre servicios de salud en el hogar para personas elegibles',
        'resources.medicaid.bullet2': 'Incluye visitas de enfermería especializada y terapia',
        'resources.medicaid.bullet3': 'Basado en necesidad médica',
        'resources.medicaid.bullet4': 'Se aplican criterios de ingresos/activos',
        'resources.medicaid.link': 'Para obtener más información o solicitar Medicaid de Florida, visite el portal ACCESS Florida del Departamento de Niños y Familias de Florida.',
        'resources.private.title': 'Seguros Privados',
        'resources.private.bullet1': 'Se aceptan la mayoría de los planes de seguros principales',
        'resources.private.bullet2': 'HMOs, PPOs y planes de atención administrada',
        'resources.private.bullet3': 'Servicio de verificación de cobertura disponible',
        'resources.private.bullet4': 'Asistencia del personal con beneficios y autorizaciones',
        'resources.insurance.note': 'Si tiene preguntas sobre su cobertura o elegibilidad, no dude en llamarnos. Podemos ayudarlo a entender los beneficios de salud en el hogar de su plan e incluso dirigirlo a los recursos correctos (como herramientas de información de Medicare o Medicaid) para obtener más información.',
        'resources.forms.section.title': 'Formularios Descargables',
        'resources.forms.section.desc': 'Para su conveniencia, proporcionamos formularios importantes que puede descargar, imprimir o completar para agilizar su proceso de atención. A continuación se muestran los formularios disponibles (en formato PDF y, donde se indica, como formularios electrónicos rellenables):',
        'resources.forms.referral.title': 'Formulario de Referencia',
        'resources.forms.referral.desc': 'Para médicos, hospitales o clínicas que refieren a un paciente. Incluye secciones para información del paciente, diagnóstico, servicios solicitados y firma del médico. Disponible como PDF imprimible y formulario electrónico.',
        'resources.forms.intake.title': 'Paquete de Admisión para Nuevos Pacientes',
        'resources.forms.intake.desc': 'Paquete integral de admisión que contiene formularios de información del paciente, consentimiento para el tratamiento, cuestionario de historial médico y derechos y responsabilidades del paciente.',
        'resources.forms.hipaa.title': 'Formulario de Consentimiento/Liberación HIPAA',
        'resources.forms.hipaa.desc': 'Autorice a nuestra agencia a compartir su información de salud protegida con miembros de la familia o cuidadores designados en cumplimiento de las regulaciones HIPAA.',
        'resources.forms.medication.title': 'Plantilla de Lista de Medicamentos',
        'resources.forms.medication.desc': 'Hoja de trabajo simple para registrar medicamentos actuales, dosis, horarios y médico que los receta. Útil para visitas al médico y emergencias.',
        'resources.forms.caregiver.title': 'Lista de Verificación Diaria del Cuidador',
        'resources.forms.caregiver.desc': 'Realice un seguimiento de las tareas diarias de cuidado como comidas, medicamentos, ejercicios, signos vitales e incluye una sección de notas para mejorar la comunicación entre miembros de la familia y el equipo de atención.',
        'resources.forms.download.note': 'Instrucciones de descarga: Haga clic en el nombre de cualquier formulario para descargarlo. Puede completarlo y enviarlo por correo electrónico/fax, o tenerlo listo para el personal durante la evaluación inicial. Si necesita un formulario en un formato diferente o tiene problemas para descargarlo, comuníquese con nuestra oficina y podemos enviárselo directamente.',
        'resources.external.section.title': 'Recursos Externos',
        'resources.external.section.desc': 'Hemos recopilado una lista de recursos externos confiables, incluyendo agencias de salud oficiales y organizaciones, para proporcionarle información y apoyo adicional.',
        'resources.external.alliance.title': 'Alianza para el Envejecimiento',
        'resources.external.alliance.desc': 'Agencia privada sin fines de lucro con sede en Miami-Dade que conecta a los adultos mayores con servicios para comidas, recreación, cuidado diurno para adultos, cuidado personal, ayuda legal y transporte.',
        'resources.external.elderaffairs.title': 'Departamento de Asuntos de la Tercera Edad de Florida',
        'resources.external.elderaffairs.desc': 'Agencia estatal dedicada a servicios para los adultos mayores de Florida, ofreciendo programas como Apoyo Nacional para Cuidadores Familiares, recursos para envejecer en el lugar y Línea de Ayuda para Adultos Mayores.',
        'resources.external.hhs.title': 'Departamento de Salud y Servicios Humanos de EE. UU.',
        'resources.external.hhs.desc': 'Departamento federal que supervisa la salud pública, los servicios de atención médica y programas como Medicare/Medicaid con información sobre políticas de salud nacionales.',
        'resources.external.cms.title': 'Centros de Servicios de Medicare y Medicaid',
        'resources.external.cms.desc': 'Agencia federal que administra Medicare, Medicaid y CHIP, proporcionando pautas detalladas de cobertura y herramientas de Comparación de Atención de Medicare.',
        'resources.external.floridahealth.title': 'Departamento de Salud de Florida',
        'resources.external.floridahealth.desc': 'Departamento de salud estatal con recursos sobre programas de salud pública, avisos de salud estatales y servicios específicos para residentes de Florida.',
        'resources.external.heart.title': 'Asociación Americana del Corazón',
        'resources.external.heart.desc': 'Organización sin fines de lucro líder que proporciona artículos educativos, consejos para una vida saludable y recursos de apoyo para la recuperación de enfermedades cardíacas y accidentes cerebrovasculares.',
        'resources.external.alz.title': 'Asociación de Alzheimer',
        'resources.external.alz.desc': 'Organización nacional que ofrece línea de ayuda 24/7, consejos para cuidadores, buscador de grupos de apoyo locales e información más reciente sobre estrategias de cuidado del Alzheimer.',
        'resources.external.ama.title': 'Asociación Médica Americana',
        'resources.external.ama.desc': 'Asociación profesional que ofrece educación en salud pública, artículos sobre condiciones de salud y herramientas como buscadores de médicos y glosarios de salud.',
        'resources.external.caregiver.title': 'Alianza de Cuidadores Familiares',
        'resources.external.caregiver.desc': 'Organización sin fines de lucro que proporciona educación, consejos para cuidadores, seminarios web, información sobre grupos de apoyo y hojas informativas para cuidadores familiares.',
        'resources.external.nia.title': 'Instituto Nacional sobre el Envejecimiento',
        'resources.external.nia.desc': 'Consejos basados en investigaciones gubernamentales sobre modificaciones del hogar, prevención de caídas y vida independiente para adultos mayores que envejecen en su hogar.',
        'resources.cta.title': '¿Necesita Más Ayuda?',
        'resources.cta.desc': 'Si está buscando algo que no está listado aquí – ya sea un formulario específico, información sobre una condición particular o orientación sobre cómo obtener atención – por favor contáctenos. Nuestro equipo en Patient\'s Choice Home Health Care siempre está listo para ayudarlo a encontrar la información o el apoyo que necesita. Recuerde, no está solo – estamos aquí para ayudarlo a navegar su viaje de atención médica en el hogar en cada paso del camino.',
        'resources.cta.button': 'Contáctenos Ahora',
        
        // Footer
        'footer.brand': 'Patient\'s Choice',
        'footer.desc': 'Proporcionando servicios excepcionales de atención médica en el hogar con compasión y profesionalismo. Su salud y bienestar son nuestras principales prioridades.',
        'footer.quickLinks': 'Enlaces Rápidos',
        'footer.connect': 'Conéctese con Nosotros',
        'footer.copyright': '© 2025 Patient\'s Choice Home Health Care. Todos los derechos reservados.',
        'footer.address': 'Dirección',
        'footer.hours': 'Horario de Oficina',
        'footer.onCall': 'Enfermeras Disponibles 24/7',
        
        // Testimonials Section
        'testimonials.title': 'Lo Que Dicen Nuestros Pacientes',
        'testimonials.subtitle': 'Escuche las experiencias de nuestros pacientes con Patient\'s Choice Home Health Care.',
        'testimonials.quote1': '"Después de la cirugía de mi mamá, Patients Choice vino a nuestra casa. Su enfermera fue increíble – compasiva, gentil y profesional. ¡Los recomiendo altamente!"',
        'testimonials.author1': 'María G.',
        'testimonials.quote2': '"Gracias a su programa de cuidado diabético, mis niveles de azúcar están bajo control. ¡He aprendido tanto!"',
        'testimonials.author2': 'Carlos M.',
        'testimonials.quote3': '"Me ayudaron a recuperarme cómodamente después de mi procedimiento cosmético. ¡Tan profesionales y discretos!"',
        'testimonials.author3': 'Emily S.',
        
        // Careers Section
        'careers.title': 'Carreras en Patient\'s Choice',
        'careers.subtitle': '¡Estamos contratando profesionales compasivos que quieren marcar la diferencia!',
        'careers.positions': 'Contratando Ahora',
        'careers.position1': 'RNs / LPNs',
        'careers.position2': 'Terapeutas Físicos y Ocupacionales',
        'careers.position3': 'CNAs / HHAs',
        'careers.position4': 'Trabajadores Sociales Médicos',
        'careers.position5': 'Coordinadores de Admisión',
        'careers.benefits': 'Beneficios',
        'careers.benefit1': 'Salario Competitivo',
        'careers.benefit2': 'Horario Flexible',
        'careers.benefit3': 'Ambiente de Trabajo de Apoyo',
        'careers.benefit4': 'Capacitación Continua',
        'careers.apply': 'Aplica Hoy',
        'careers.applyDesc': 'Envía tu currículum a <a href="mailto:careers@patientschoice.com" class="contact-link">careers@patientschoice.com</a>',
        'careers.contact': '¿Interesado en ser parte de nuestro equipo?',
        'careers.contactDesc': '¡Contáctanos ahora para más información!',
        
        // FAQs Section
        'faqs.title': 'Preguntas Frecuentes',
        'faqs.subtitle': 'Encuentre respuestas a preguntas comunes sobre nuestros servicios y atención.',
        'faqs.question1': '¿Qué es la atención médica en el hogar?',
        'faqs.answer1': 'Atención médica proporcionada en su hogar por enfermeras, terapeutas y asistentes bajo la dirección de un médico.',
        'faqs.question2': '¿Quién califica?',
        'faqs.answer2': 'Pacientes que están confinados en casa y requieren atención especializada intermitente.',
        'faqs.question3': '¿Está cubierto por el seguro?',
        'faqs.answer3': '¡Sí! Medicare, Medicaid y la mayoría de los seguros privados cubren servicios calificados.',
        'faqs.question4': '¿Ofrecen servicios de pago privado?',
        'faqs.answer4': 'Sí, especialmente para recuperación cosmética y atención de conserjería.',
        'faqs.question5': '¿Cómo empiezo?',
        'faqs.answer5': '¡Llámenos o haga que su médico envíe una referencia. Nosotros nos encargamos del resto!',

        // Contact Form Placeholders and Labels
        'contact.name.placeholder': 'Ingrese su nombre completo',
        'contact.email.placeholder': 'Ingrese su correo electrónico',
        'contact.phone.placeholder': 'Ingrese su número de teléfono',
        'contact.message.placeholder': 'Cuéntenos sobre sus necesidades',
        
        // Contact Form Service Options
        'contact.service.optgroup.nursing': 'Servicios de Enfermería Especializada',
        'contact.service.option.nursing': 'Cuidado de Enfermería Especializada',
        'contact.service.option.medication': 'Manejo de Medicamentos',
        'contact.service.option.wound': 'Cuidado de Heridas',
        'contact.service.option.monitoring': 'Monitoreo de Salud',
        
        'contact.service.optgroup.therapy': 'Servicios de Terapia',
        'contact.service.option.physical': 'Terapia Física',
        'contact.service.option.occupational': 'Terapia Ocupacional',
        
        'contact.service.optgroup.personal': 'Servicios de Cuidado Personal',
        'contact.service.option.daily': 'Asistencia en Actividades Diarias',
        'contact.service.option.hygiene': 'Cuidado de Higiene Personal',
        'contact.service.option.mobility': 'Asistencia de Movilidad',
        
        'contact.service.optgroup.other': 'Otros Servicios',
        'contact.service.option.caregiver': 'Relevo del Cuidador',
        'contact.service.option.coordination': 'Coordinación de Cuidados',
        'contact.service.option.other': 'Otros Servicios',

        'contact.address': 'Dirección',
        'contact.license': 'Licencia #299992327',

        // Contact Information
        'contact.info.phone': '(305) 225-5353',
        'contact.info.fax': '(305) 225-5306',
        'contact.info.email': 'info@patients-choice.com',
        'contact.info.careers_email': 'careers@patientschoice.com',
        'contact.info.license': 'Licencia #299992327',
        'contact.info.address.line1': '7205 NW 19th Street, Suite 201',
        'contact.info.address.line2': 'Miami, Florida 33126',
        'contact.info.hours': 'Lunes–Viernes, 9 AM – 5 PM',
        'contact.info.callToday': 'Llame Hoy:',
        'contact.info.faxLabel': 'Fax:',
        'contact.info.emailLabel': 'Correo Electrónico:',
        'contact.info.companyName': 'Patients Choice Home Health Agency',
    }
};

// Function to set the language
function setLanguage(lang) {
    // Update HTML lang attribute
    document.documentElement.lang = lang;
    
    // Update all elements with data-translation-key attribute
    document.querySelectorAll('[data-translation-key]').forEach(element => {
        const key = element.getAttribute('data-translation-key');
        if (translations[lang] && translations[lang][key]) {
            // Handle optgroup labels specially
            if (element.tagName.toLowerCase() === 'optgroup') {
                element.label = translations[lang][key];
            }
            // Use innerHTML for elements that contain HTML
            else if (key === 'hero.title' || key === 'careers.applyDesc') {
                element.innerHTML = translations[lang][key];
            }
            // Handle placeholders
            else if (element.hasAttribute('placeholder')) {
                element.placeholder = translations[lang][key];
            }
            // Default text content update
            else {
                element.textContent = translations[lang][key];
            }
        }
    });
    
    // Store language preference
    localStorage.setItem('preferredLanguage', lang);
    
    // Update active language button
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.remove('active');
        if (btn.getAttribute('data-lang') === lang) {
            btn.classList.add('active');
        }
    });
}

// Initialize language
document.addEventListener('DOMContentLoaded', () => {
    // Get preferred language from localStorage or default to English
    const preferredLanguage = localStorage.getItem('preferredLanguage') || 'en';
    setLanguage(preferredLanguage);
    
    // Add click event listeners to language buttons
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            const lang = btn.getAttribute('data-lang');
            setLanguage(lang);
        });
    });
}); 